/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/m/mico2178/baxter_ws/src/project/srv/painter.srv
 *
 */


#ifndef PROJECT_MESSAGE_PAINTER_H
#define PROJECT_MESSAGE_PAINTER_H

#include <ros/service_traits.h>


#include <project/painterRequest.h>
#include <project/painterResponse.h>


namespace project
{

struct painter
{

typedef painterRequest Request;
typedef painterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct painter
} // namespace project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::project::painter > {
  static const char* value()
  {
    return "830abc81a55f943fae87b31df2808dfc";
  }

  static const char* value(const ::project::painter&) { return value(); }
};

template<>
struct DataType< ::project::painter > {
  static const char* value()
  {
    return "project/painter";
  }

  static const char* value(const ::project::painter&) { return value(); }
};


// service_traits::MD5Sum< ::project::painterRequest> should match 
// service_traits::MD5Sum< ::project::painter > 
template<>
struct MD5Sum< ::project::painterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::project::painter >::value();
  }
  static const char* value(const ::project::painterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::project::painterRequest> should match 
// service_traits::DataType< ::project::painter > 
template<>
struct DataType< ::project::painterRequest>
{
  static const char* value()
  {
    return DataType< ::project::painter >::value();
  }
  static const char* value(const ::project::painterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::project::painterResponse> should match 
// service_traits::MD5Sum< ::project::painter > 
template<>
struct MD5Sum< ::project::painterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::project::painter >::value();
  }
  static const char* value(const ::project::painterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::project::painterResponse> should match 
// service_traits::DataType< ::project::painter > 
template<>
struct DataType< ::project::painterResponse>
{
  static const char* value()
  {
    return DataType< ::project::painter >::value();
  }
  static const char* value(const ::project::painterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROJECT_MESSAGE_PAINTER_H
